### ISSUE TITLE
Use on-demand builder for photo functions

### ISSUE THREAD

**Issue by regisphilibert** [andreweick/eick.com#116]
Currently the photo.js function URL returns a handler, it should return a builder now that we found a way to bypass query string parameters (not supported by builders)

https://answers.netlify.com/t/how-to-use-url-parameters-with-on-demand-builders/40432

**Comment by andreweick** [comment]
@regisphilibert I know you are talking about a different part of the code base, but I could re-write the backend API to accept a URL path (rather than a querystring) if that would help.  (Although again, I know you are talking about the JS function not the GOLANG API)

#GoHabs

**Comment by regisphilibert** [comment]
Hi @andreweick yes, this is about us not being able to fetch the name parameter from the serverless function URL so I can't use `.netlify/function/photo/?name=filename` I have to pass it to the url and retrieve it by splitting the url from `.netlify/function/photo/filename`. 

https://github.com/andreweick/eick.com/blob/a7725b3a7b11c2429bea845beee7b6fa1ba27ba4/functions/photo.js#L17-L27

Your API is good here (once I have the filename I can use your endpoint no problem), this issue is really about a Netlify builder limitation.
