### ISSUE TITLE
Mux.js and Video JS kit

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#117]
Add  Video JS kit https://docs.mux.com/guides/video/playback-videojs-with-mux for playing videos from mux.com

**Comment by andreweick** [comment]
@regisphilibert This isn't for this sprint, but I'm really tired of YouTube and this weekend I saw mux.com linked from daringfireball so I'm trying it --  

To integrate it into the site would be making a short code and styling, etc, but just to try it out, it seems I would add:

```
// script
<script src="https://unpkg.com/@mux/videojs-kit@0.1/dist/index.js"></script>
// css
<link rel="stylesheet" href="https://unpkg.com/@mux/videojs-kit@0.1/dist/index.css">
```

and then 

```
<video 
  id="my-player" 
  class="video-js vjs-16-9" 
  controls 
  preload="auto" 
  width="100%"
  data-setup='{}'
>
  <source src="2HlZKwXuxShYALFeHzrErOs01NzFnO62qgf2vS47Fhck" type="video/mux" />
</video> 
```

in a post.

Again, just to test, in which file should I "hardcode" the includes from code block 1?

**Comment by andreweick** [comment]
#GoHabs

**Comment by regisphilibert** [comment]
> I really like that, as a country, you renamed all the fast food restaurants to "Wah Wogers" after the great goaltending in the '93 cup.

I really did not know that :)

**Comment by andreweick** [comment]
@regisphilibert I was going to make a joke about the soccer game, but I'm not sure you know me well enough t o get the humor, and I don't want to offend :-)

I'd like to add this as a "next sprint" item, but short term, can I just add the "script tags" to https://github.com/andreweick/eick.com/blob/6b6b3416ec1002fcfc876b4cbe09d0cd377f10a5/layouts/partials/head.html and the "<video />" tag to a post?

**Comment by andreweick** [comment]
@regisphilibert ok, that did work to hack it in -- I'll hack it in for now but leave a marker to revert it later with a short code...
