### ISSUE TITLE
Redirects from base URL

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#119]
I expect this is a result of debugging, but some URLs direct off the site:

- [x] All the links on the front page seem to link to a netlify URL (e.g. https://60e48f92b9a6530007edeedf--www-eick-com.netlify.app/posts/2021-06-23-mclean-girls-soccer-game-another/)
- [x] The photos link to the builder url (e.g. https://www.eick.com/.netlify/functions/photo/yosemite_scenery-2.jpg) -- is it possible to get these to link to https://www.eick.com/photo/yosemite_scenery-2.jpg?)

**Comment by regisphilibert** [comment]
I'll take a look at those!
