### ISSUE TITLE
Allow audio shortcode to play multiple tracks with album art from posts

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#123]
@regisphilibert Is this (https://521dimensions.com/open-source/amplitudejs) the player for the audio shortcode on my site?

I know you asked me previously, and I swore I'd never have more than 1 track per post, but I've evolved :-)

I'm thinking something like https://521dimensions.com/open-source/amplitudejs/docs/examples/multiple-songs.html, with the songs, album art, etc as "yaml data" on the post?

Could even use imgix to format an "album cover" to the correct dimensions -- something like

```
https://edc.imgix.net/2021-04-08-piano-fingers.jpg?h=500&w=500
```

![piano](https://edc.imgix.net/2021-04-08-piano-fingers.jpg?h=500&w=500)

**Comment by regisphilibert** [comment]
@andreweick I have a straight forward implementation for this if we only have one player per page (It will potentially list several playable tracks of course).

But in order for you to be able to add multiple players (multiple shortcode) we have to refactor a lot of things. 
AmplitudeJS only allow one init per page, with whitch you can declare all the songs of one page and somehow reference them in each players, but in Hugo each shortcode is isolated from the others, so I wouldn't have a convenient way to merge all their data in order to build this list of songs for the whole page.

Bottomline: 
1. We only allow one `audio` shortcode/player per page (with one or more song in one player) I can go ahead and start on this.
2. We need more than one player per page, I have to spend considerably more time on this and potentially drop AmplitudeJS as a solution.

**Comment by andreweick** [comment]
@regisphilibert excellent!  Great work!  Let's go with option 1 -- 

The "one shortcode // multiple tracks" will solve my use case beautifully.

**Comment by regisphilibert** [comment]
Ok so we have a PR in place and a private example page: https://deploy-preview-144--www-eick-com.netlify.app/multiple-songs/

I kept the UI very simple as you can see... But if multiple songs are detected, we list them as a "play" button for each.

### Cover
I still have to add the cover. But could you clarify, do you need one per song, or one per player? Now I'm not sure you want a COVER for the whole playlist or per song?
### UX
Now that we are limiting to one player per page, the point of having a shortcode holding the songs loses its value and makes the UX a bit tedious, for example this is the best "shortcode ux" I could come up with when multiple songs:

```
{{< audio title="Libby Piano Run 1, Libby Piano Run 2, Libby Piano Drill" file="https://cdn.eick.com/audio/2021-07-10-run-1.mp3, https://cdn.eick.com/audio/2021-07-10-run-2.mp3, https://cdn.eick.com/audio/2021-07-10-drill-1.mp3" >}}
```

Each parameter holds a list of comma separated value. So you can enter 3 titles and 3 files in matching order. It's ok I guess... but could lead to errors when more than 3 songs and I'm not taking about adding a 3rd parameter...

I guess we could now switch to using page meta data like this:

```
title: A Recital
songs:
- title: Libby Piano Run 1
   file: https://cdn.eick.com/audio/2021-07-10-run-1.mp3
   cover: https://cdn.eick.com/audio2021-07-10-run-1.jpg
[...]
```

We'd still use a shortcode so you retain control on "where" it appears in the page body, but it will pull its song data (and other) from the page's `.songs` params so all we'd need in the page body is a simple `{{< audio >}}`.

**Comment by andreweick** [comment]
@regisphilibert 1 cover per playlist (and one playlist per post)

(and for the cover, I was thinking of using IMGIX and putting the text onto the image, but I know that will work)

I like the idea of using the YAML front-matter.  Yup, good thought -- the front matter would have the data, and the shortcode would control where on the page it is

**Comment by andreweick** [comment]
(@regisphilibert also, could you make the "player-bar" scrubbable so I can "drag the song forward"?

I like the rest of the rest !

Again, I was using

https://edc.imgix.net/2021-04-08-piano-fingers.jpg?h=500&w=500

as a cover image to test with

**Comment by regisphilibert** [comment]
Ok I made the Front Matter populate the songs/playlist data as illustrated here: https://github.com/andreweick/eick.com/blob/123-multi-audio/content/multiple-songs.md
and seen in action here: https://deploy-preview-144--www-eick-com.netlify.app/multiple-songs/

I added the field to the CMS (not sure you're using it...)

I also added the cover image with the title of the playlist as overlay. You can tweek the text styling to your convenience by reading [this](https://docs.imgix.com/apis/rendering/text) and toying the following code piece:

https://github.com/andreweick/eick.com/blob/cabbbcc401e1ee81c3305bb098cc90b59f12dfe0/func/GetPagePlaylist.html#L27-L31

I'll now move on to

> could you make the "player-bar" scrubbable so I can "drag the song forward

**Comment by regisphilibert** [comment]
Turns out amplitude has a very straight forward way to add this. But... you have to style the `input[range]` which is... a pain. I've styled it as much as I can without entering the prefix rabbit hole... Let me know if it's satisfactory.

**Comment by andreweick** [comment]
@regisphilibert this is where I get lost in your French to English translations.  If by satisfactory you mean **AWESOME** than I say *yes Sir -- ready for a PR!*

I will be using the CMS, I'm just trying to 'back convert' into the new short codes.  Go ahead and merge away when ready
