### ISSUE TITLE
mux.com shortcodes

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#125]
I'm using MUX.com w/ signed secure URLs from now on (no more YouTube!) --

## Reference
https://www.npmjs.com/package/@mux/mux-node

## Description
I've set up mux.com with private videos and VideoJS kit.  I've added a netlify function (~/functions/sign-video-url.js) which will sign the URL's given the environment variables I set up.  What I don't know how to do is call the function and pass in parameters.  I also don't know how to promise // async // await, but that's a bug for another day.

In media-test, I have a "private video" -- the other two videos are public and just to test with if -- I'm sure the URL's have expired in the private video.

I tried to make it so that the JSON struct has the URL's that can go right into the javascript in the post.

The optional parameters (thumbnail-time-offset, expire-time, aspect-ratio) pass into the netlify function, I'll hook them up later.

I tried t o derive the aspect-ratio from the video (see promise/async/await ☝️ ) but couldn't get it working in the function, but I expect you'll need to change the markup depending on what aspect it is.

To hack it in

I'd like to add a shortcode like 👇 

```
{{< mux elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk thumbnail-time-offset="10" expire-time="2h" aspect-ratio="16:9" >}}
```

The second parameter is the playbackID -- that needs to be passed to the netlify function

The function will return a JSON struct

```json
{
  "src": "elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk?token=eyJhbGciOi...",
  "srcTimelineHover": "https://image.mux.com/elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk/storyboard.vtt?token=eyJhbG....",
  "srcStoryboard": "https://image.mux.com/elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk/storyboard.jpg?token=eyJ...",
  "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCI...",
  "tokenStoryboard": "eyJhbGciOiJSUzI1NiIsInR5cCI...",
  "srcThumbnail": "https://image.mux.com/elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk/thumbnail.jpg?token=eyJhbGciOiJSUzI1NiIsI...",
  "tokenTumbnail": "eyJhbGciOiJSUzI1Ni..."
}
```

And the corresponding markup

```
<video 
  id="my-playerPrivate" 
  class="video-js vjs-16-9" 
  controls 
  preload="auto" 
  poster="https://image.mux.com/elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk/thumbnail.jpg?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRRYTNLOXhyNWJRcHZ6UHFWTEhocTZZcWVUc1lyMDJNaHUwMFZvVWJJbDJhTSJ9.eyJleHAiOjE2MjcyNTg4NjUsImF1ZCI6InQiLCJzdWIiOiJlbGVjTWQ1NmE3MDJxVjdwV1VDUE8yUGVqZjAxUnZ1S0tGOUVCcnRzN2pkcmsifQ.BUcZWoVhc2uZvTomOmKvYRRR2NyiKjm7_hh45oo_pO7U71jazz9E7D1GfTg0iY-XDONrr6SSh262WYypRLhKJB288poW3YlO21OQ2jO0NXnclAUvW0E3g45mSNf7GQLS9BNN-VZkPY-Aqa7ihU7C_I202qJiQnNCfNrHzP93_ck7Fbhzz-GznyGjOM7BAv04Gxh7segNfjWZRR5AWTYVnoZvJcAA1MPlvj--qhMEeQm_GQ3VzdjiL4U6D0hjvBfm-t5MFtm44QFk32RnPRz8D0Ri4Pzyaw-Kt9Z0iImmYHcQR-nDwbiz9n9XDTmqKqeo6jpBavgtDuVeP0ssW_qYew"
  width="100%">
</video>

<script>
const playerPrivate = videojs('my-playerPrivate', {
  plugins: {
    mux: {
      debug: false,

      data: {
        video_title: 'Zoom Piano Recital'
      }
    }
  }
});

playerPrivate.src({
  src: "elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRRYTNLOXhyNWJRcHZ6UHFWTEhocTZZcWVUc1lyMDJNaHUwMFZvVWJJbDJhTSJ9.eyJleHAiOjE2MjcyNjAwNTgsImF1ZCI6InYiLCJzdWIiOiJlbGVjTWQ1NmE3MDJxVjdwV1VDUE8yUGVqZjAxUnZ1S0tGOUVCcnRzN2pkcmsifQ.LmeVi5GDpYjFnOtmjjQTGaHWnEgmJ450rG_vensE2ayAIw3d5FG1L3vHkQ9s6TUgBah-DmH_1zFZPWe1hqLU9f7-7VYf4imsW5dRMPf2x3iRUqRJkHqw05w2VCC_EEH7jCp0pHKegQ7DvskDZzfi_ZTF_YWgkSTh8VLI8eshh--gG8JhYC9CDzv46TVPAXEFB1_FjYXe8ydGvsCnq86LlHLHYCi4uFp0P1cOmiY7gtflLEfqShla6cVlibJH_wsGbxLIJDdBZAyIGADZ_u3Tt0hPkGjh_ry_1732MwPnHo_LU0HMyJzy9axYWwWYN40xh3RcUPYruw-aIONR44uY3A",
  type: "video/mux",
});

playerPrivate.timelineHoverPreviews({
  enabled: true,
  src: "https://image.mux.com/elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk/storyboard.vtt?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRRYTNLOXhyNWJRcHZ6UHFWTEhocTZZcWVUc1lyMDJNaHUwMFZvVWJJbDJhTSJ9.eyJleHAiOjE2MjcyNTg4NjUsImF1ZCI6InMiLCJzdWIiOiJlbGVjTWQ1NmE3MDJxVjdwV1VDUE8yUGVqZjAxUnZ1S0tGOUVCcnRzN2pkcmsifQ.QoC7-CjOAAvTV3ilfdz7s11nvA-XZItLQUL_UIICb4S-Ewz3GIynCnlzObty-V0ZUbvYiBXF194l7a056oTJoxg_sgzn87xlHUH0QimxS7ov2cXFGPJgi35QlSFfs12brPh0-PMqR4FXld4X4PVsn2ntQsEnPYlUhMIP7sTIAZXh3gT6efnU1LJKbh-KfVpeezpKfiZRmsmigcoYyA1HOQcKXgoxhZrgLKUwiO6pzUFI1yaTImnhPqy6SKvslMzDd0ey6POoLjeQzDF2mcib_qrbGD1jRUYG1yxXYjPFO-JSRc5haj0K5B5c5oUvkGBdzqoXO3V-IUJG7hqpqapLPA"
});

</script>

[Storyboard for video](https://image.mux.com/elecMd56a702qV7pWUCPO2Pejf01RvuKKF9EBrts7jdrk/storyboard.jpg?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRRYTNLOXhyNWJRcHZ6UHFWTEhocTZZcWVUc1lyMDJNaHUwMFZvVWJJbDJhTSJ9.eyJleHAiOjE2MjcyNTg4NjUsImF1ZCI6InMiLCJzdWIiOiJlbGVjTWQ1NmE3MDJxVjdwV1VDUE8yUGVqZjAxUnZ1S0tGOUVCcnRzN2pkcmsifQ.QoC7-CjOAAvTV3ilfdz7s11nvA-XZItLQUL_UIICb4S-Ewz3GIynCnlzObty-V0ZUbvYiBXF194l7a056oTJoxg_sgzn87xlHUH0QimxS7ov2cXFGPJgi35QlSFfs12brPh0-PMqR4FXld4X4PVsn2ntQsEnPYlUhMIP7sTIAZXh3gT6efnU1LJKbh-KfVpeezpKfiZRmsmigcoYyA1HOQcKXgoxhZrgLKUwiO6pzUFI1yaTImnhPqy6SKvslMzDd0ey6POoLjeQzDF2mcib_qrbGD1jRUYG1yxXYjPFO-JSRc5haj0K5B5c5oUvkGBdzqoXO3V-IUJG7hqpqapLPA "Figure 1: Storyboard")
```

**Comment by andreweick** [comment]
Adding the javascript I hardcoded for reference

```js
<video id="my-player" class="video-js vjs-16-9" controls preload="auto" width="100%" data-setup='{"timelineHoverPreviews": true}'>
  <source src="DZUbscooFImH800Zod01zZx8VI4Sf5Wx900CIk1VvqQedo" type="video/mux" />
</video>  
```

![Storyboard just for fun](https://image.mux.com/DZUbscooFImH800Zod01zZx8VI4Sf5Wx900CIk1VvqQedo/storyboard.jpg) is a neat addition for fun

```
https://image.mux.com/DZUbscooFImH800Zod01zZx8VI4Sf5Wx900CIk1VvqQedo/storyboard.jpg
```

**Comment by andreweick** [comment]
---

I hacked in mux video player // video js -- on the mux-video-player branch

Both of the videos below use the "public" method -- these are just for test, I'd like to migrate to the "signed" method

https://www.eick.com/posts/libby-and-nargol-play-bach/

https://www.eick.com/posts/alkaline-family-fight-night/

I did this by hardcoding the include in head.html and then the javascript.  

This issue is to remove the "hardcoding" from head.html and add a shortcode

---

I think 

https://raw.githubusercontent.com/andreweick/eick.com/mux-video-player/content/posts/2021-06-19-zoom-piano-recital.md 

is the closest -- it has a signed URL.

A bunch more learnings:  The two videos above are public, while http://localhost:1313/posts/2021-06-19-zoom-piano-recital/ is a private video that uses signed (and timed) URLs.  I've pre-signed the URL's to be valid for a couple months, but in the Javascript you'll see various TOKEN that need to be generated and passed.

So need to distinguish "private" videos from "public" -- in that if it's public it will error out if you pass in a token...

The videos above have a nice scrubber (and storyboard) -- when you scrub the video the thumbnail shows up of what is in the video at that point -- I can't get that to work with signed URL's but it says it should -- so I'll keep working/

I'm not sure how this should work -- I think the idea is that each user of the site triggers the "signing" function, so each user gets a specific URL?  Does that mess up the CDN caching?

I'm working on adding a netlify function that will generate a signed URL for the player, so the page will have to call a signing function that will return a JSON object that contains the URL

**Comment by andreweick** [comment]
historical as I debugged)

This issue is to create the mux.com shortcakes for Hugo, and finish the netlify function which signs the URLs.  

I've added to the media test post, 3 videos, "normal" (public), portrait, and private (signed).  The signed URLs need to get signed so you pass a "publicId" and a "token".  I've started the netlify function (~/functions/sign-video-url.js) which will sign the URL.  I could not figure out how to call my netlify function from my page, nor how to pass parameters to the function.

## Tasks

**Comment by regisphilibert** [comment]
So we have a shortcode which for now only passes a mux video `id` and a `private` toggle.
Examples (along with the following comments) are here: https://deploy-preview-143--www-eick-com.netlify.app/mux/


If private is set then the js (assets/js/mux.js) will fetch the sign-video-url functions and use the returned `data.src` and `data.srcThumbnail`,
if not, we'll just return:

```js
{
  src: id,
  srcThumbnail: "https://image.mux.com/" + id + "/thumbnail.png?time=16",
}
```

### Questions:
1. We're hardcoding the title, I assume this will come from a shortcode attribute as well?
2. I'm not sure I understand where the `thumbnail-time-offset` would be in play?
3. I'm using `/.netlify/functions/sign-video-url.js` but we also have a `assetid2infos.js`, any preference?
3. The shortcode set an expire time, should we pass it as a parameter to the serverlerss function as well? Then again I'm not sure why we need this per shortcode... Coudn't it be a global setting we set?
4. I have error handling on the client, but we need one on the serverless function as well. (for now it returns the same structured data only with ULR pointing to errors). I couldn't find [here](https://docs.mux.com/guides/video/secure-video-playback#3-generate-a-json-web-token) how we're supposed to handle and erroneous video ID for example...

**Comment by andreweick** [comment]
@regisphilibert 

1. Yes, please add the title to the shortcode -- good catch
2. This really confused me as well -- The idea is if you want the thumbnail to be "30 seconds into the video" -- however, with "signed URL's", the whole URL is signed, (with the time hack offset) so that's why I needed to pass it in.  I figured this out Sunday night late, and ran out of time to implement it, but (when I do implent it), I'll populate the JSON object correctly.
3. sign-video-url.js.  Assetid2info.js was me trying to program "Given an AssetID get a PlaybackID" -- but the function call returned a promise, and I had no idea how to wait for a promise 😃   No Really, I spent a good 2 hours trying to get it to work https://github.com/andreweick/eick.com/blob/c92a11f7fb435e3b0d9fcb5e3074a28b28ab7d1a/functions/assetid2info.js#L21. On reflection, I think it's cleaner to only post only 'private' video links, so the shortcode is 'cleaner' (making no decisions) -- if I ever do figure out promises, I only need to change the function, since the URL's are in the JSON object, the shortcode doesn't need to know if it is public or private (just that the JSON URL's are correct)
4. My thought was to have the time-to-live as an (optional parameter) -- that way if I ever have an 8 hour video (or a video that is longer than the time out) I could set it in the markup, not globally.  (Probably over - engineering on my part)
5. Error Handling...Error handling -- do you have any reference things I can read on this concept?  I'm not familiar with it.  Yes, Good Catch, If I could have gotten Assetid2info.js to work, that would have checked handled errors more gracefully.  Let's leave out checking for now (and assume the playbackID is valid) -- maybe I'll write a GitHub action that checks the PlaybackID's are valid

Geez "Error Handling" -- must be a Canadian thing.

Yeah, I struggled with the "signed" vs "public", and came down to "if everything is private", then the code / shortcode would be simpler...And if I did want to do "public" later on, I tried to make it just the function that would change.

**Comment by andreweick** [comment]
(In a further sprint I want to make the "private URL's" stronger -- e.g. integrate netlify identity, only works if served from "eick.com", etc

**Comment by regisphilibert** [comment]
1. I passed the title to the Video player invocation but not sure what's the impact on the front-end...
2. I'm not sure I understood what I should do though :)
3. Got it, yeah promises are hard... I got rid of the private short-code settings.
4. Ok shortcode can take an optional parameter of expire-time which will default to `2h`
5. Well I guess it might come with... promises... But the idea is to populate the HTTP response with some sort of error message (and potentially status code) so the front-end can read the error and behave accordingly.

> if I ever do figure out promises

Or you could build those functions in Go... Netlify serverless functions supports Go and Mux has a [Go SDK](https://github.com/muxinc/mux-go)...
The only problem I ran into (and could not figure out as a go early beginner) is how to properly invoke `go install` etc... 
But this might make more sense to you: https://docs.netlify.com/functions/build-with-go/

BTW the sign-video-url function returns a lot of unused data:
```javascript
{
// Actually used V
src: playbackID + "?token=" + token, 
srcThumbnail: "https://image.mux.com/" + playbackID + "/thumbnail.jpg?token=" + tokenThumbnail,
// For debugging purposes V
tokenValidFor,
// Unused data V
srcHls: "https://stream.mux.com/" + playbackID + ".m3u8?token=" + token,
srcTimelineHover: "https://image.mux.com/" + playbackID + "/storyboard.vtt?token=" + tokenStoryboard,  
srcStoryboard: "https://image.mux.com/" + playbackID + "/storyboard.jpg?token=" + tokenStoryboard,
token: token,
tokenStoryboard: tokenStoryboard, 
tokenTumbnail: tokenThumbnail
}
```
That might be useful later though...

**Comment by andreweick** [comment]
Ha!  Ok

1. Yes, I agree, I couldn't figure out what the title did, I thought I was just being HTML stupid though so I didn't want to say anything in case you'd think me naive. 👍 
2. If you could just take the srcThumbnail URL and us that as the poster image -- Someday I'll figure out signing  and it will "just work" (famous last words)

You know, I thought of doing it in go, but then the "npm run dev:netlify" (netlify cli) seemed like that would only work javascript -- so (don't laugh), I wrote my original test in go (45 minutes), and then converted it to node (infinity hours)

Good catch, I should skinny down that JSON.

Just take the WIP off the PR when your ready and I'll go from there

**Comment by regisphilibert** [comment]
1. Ok well we have a default, but a `title` can always be passed to the shortcode to overwrite it...
2. Ok using the signed `srcThumbnail` when retrieved as the video html element poster attribute.

> You know, I thought of doing it in go, but then the "npm run dev:netlify" (netlify cli)...

Well that might be the catch indeed. Somehow your CLI needs to tell netlify where to find some stuff (go path etc...) and run some stuff before deploying. This article uses a `.make` file to run different scripts... https://hackersandslackers.com/deploy-serverless-golang-functions-with-netlify/
