### ISSUE TITLE
I broke the build

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#131]
Régis -- I broke the build :-( -- I was doing some pushes and I (must have) deleted some critical files -- I'm now getting (pasted :points-down:)

-- I suppose related to #127 ? 

```
5:07:48 PM: Start building sites …
5:07:49 PM: WARN 2021/07/18 21:07:49 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
5:08:14 PM: ERROR 2021/07/18 21:08:14 POSTCSS: failed to transform "css/style.css" (text/css): resource "css/css/style.css_b5720a2b10622ea478a38d3d6b170f3d" not found in file cache
5:08:14 PM: Total in 29340 ms
5:08:14 PM: Error: Error building site: JSBUILD: failed to transform "tnd-search/instantsearch/index.jsx" (text/jsx): Could not resolve "@meilisearch/instant-meilisearch" (mark it as external to exclude it from the bundle)
```

(https://app.netlify.com/sites/www-eick-com/deploys/60f497d5f4d13b3a8777f1f5)

**Comment by regisphilibert** [comment]
Hi @andreweick to save time on build time on Netlify we deploy assets on local using `npm run deploy`, and commit them (hence #127).

As the Netlify build is instructed to look for those committed files rather than build them, it will fail if they're not found or their hash do not match.

**Comment by andreweick** [comment]
@regisphilibert Thanks, ok, That makes sense.  I'll update my workflow to run an npm run deploy, and then push main (if I make non-content changes)

I npm run deploy'd, then pushed the new (and deleted css changes)

I'm still getting an error though --  👇   (or on netlify on the main branch log) -- I must have mucked the package.json and deled the search package...


```
7:44:56 PM: ​
7:44:56 PM: ────────────────────────────────────────────────────────────────
7:44:56 PM:   2. build.command from netlify.toml                            
7:44:56 PM: ────────────────────────────────────────────────────────────────
7:44:56 PM: ​
7:44:56 PM: $ hugo --minify -e cached
7:44:56 PM: Start building sites …
7:44:57 PM: WARN 2021/07/19 23:44:57 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
7:45:23 PM: Total in 27447 ms
7:45:23 PM: Error: Error building site: JSBUILD: failed to transform "tnd-search/instantsearch/index.jsx" (text/jsx): Could not resolve "@meilisearch/instant-meilisearch" (mark it as external to exclude it from the bundle)
7:45:23 PM: ​
7:45:23 PM: ────────────────────────────────────────────────────────────────
7:45:23 PM:   "build.command" failed                                        
7:45:23 PM: ────────────────────────────────────────────────────────────────
```

**Comment by andreweick** [comment]
parenthetically, just knowledge check.  The build command that netlify runs (netlify.toml // command = "hugo --minify -e cached" is a minimal build set, while (HUGO_ENV=production bin/hugo* --gc --minify --cleanDestinationDir) from the package.json is the "full re-write / rebuild" -- the intuition being that building the file on your laptop and committing it saves build time on the server) -- that makes sense --

**Comment by andreweick** [comment]
@regisphilibert sorry to keep bugging you on this, but any thing I should try?

**Comment by regisphilibert** [comment]
I thought you resolved this by adding back the `@meilisearch/instant-meilisearch` package to package.json

**Comment by andreweick** [comment]
@regisphilibert Ahh -- ok, yes, I added it back by just editing package.json, when I did an npm run deploy it overwrote and "removed" the line from package.json.

Do I do some NPM command to add it?

**Comment by regisphilibert** [comment]
let me try

**Comment by regisphilibert** [comment]
More was missing... but `npm run deploy` did not change the package.json after I manually installed the 3 missing deps... Just pushed...

**Comment by andreweick** [comment]
Thank you so much!  Sorry (I made) an emergency.  Maybe during our kickoff for Sprint 3 you can tell me what I messed up (besides npm run deploy)


Holy Petes I think there is some log going crazy -- look at the build logs on netlify (I just had to close the tab due to memory limits). (@regisphilibert )

**Comment by regisphilibert** [comment]
I've got to run, turns out other dependencies are missing (the one used by netlify build plugin). Maybe you can find in the history the prestine package.json before it was tampered with?

**Comment by andreweick** [comment]
Will do. I'll look further and ping tomorrow if I can't find it. Thanks for the help

**Comment by andreweick** [comment]
@regisphilibert reverted a package.json and pushed -- it works now

/close
