### ISSUE TITLE
Change the "photos" page to be a grid of photos

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#133]
Change https://www.eick.com/photos/ to be a grid of photos (like a contact sheet) rather than a list with thumbnails.  Show the image name underneath the photo. (Maybe we could get more than 10 per page!).  Put the name of the photo underneath for easy copy / pasting into a post

(would be cool if you could make it as the markdown so I could just copy it as is)

**Comment by regisphilibert** [comment]
@andreweick I created a PR for you to review: https://deploy-preview-137--www-eick-com.netlify.app/photos (#137)

I took this opportunity to:
- update the dev meta (hugo vs netlify ODB) to be more discreet and not show up in production.
- Update pagination to 40, pagination cannot be responsive, so this will look the best on wide screen when we have a grid of 8 cells per 8 rows. 

> (would be cool if you could make it as the markdown so I could just copy it as is)

This is what I'm not 100% grasping. You need to be able to easily copy the title of the image but what do you mean by _as the markdown_?

**Comment by andreweick** [comment]
@regisphilibert Sure -- the use case is that I have a certain photo I'm looking for -- once I find it, to have "what I should copy" if I want to link to it, I can copy the link (I put markdown, confusingly, I meant shortcode)

If I wanted to include https://www.eick.com/photo/05-20-market-day-63.jpg/

{{</* figure src="/05-20-market-day-63.jpg" caption="Libby at Colonial Market */>}}

**Comment by andreweick** [comment]
(And of course the caption is left blank on this one since it wasn't returned in the JSON  from the API)

**Comment by regisphilibert** [comment]
@andreweick I'm having a hard time easing up the copy for you. I created a separate issue (#138) for another sprint.
If the `https://deploy-preview-137--www-eick-com.netlify.app/photos` works as it is, I'll fix it and merge it in production)
