### ISSUE TITLE
Don't show specific tags on home page

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#136]
Anything tagged with (some user defined tag) don't show on home page

**Comment by regisphilibert** [comment]
If we use tags like this:
Something like:
```yaml
---
title: Libby Plays Beethoven
date: 2019-12-21T05:00:00.000Z
tags:
  - piano
  - audio
  - exclude
---
Hugo will make it surface whenever we invoke tags like here: https://www.eick.com/tags/

But we could use a front_matter field... like `hp_exclude: true` or something.

**Comment by regisphilibert** [comment]
>  just take it off the home page
Yes I understand.

**Comment by regisphilibert** [comment]
Took the liberty of merging this has it had 0 impact on front-end. You now have a toggle on NetlifyCMS's posts entries called "Exclude from Homepage"
