### ISSUE TITLE
Deactivate branch deploy on Netlify?

### ISSUE THREAD

**Issue by regisphilibert** [andreweick/eick.com#141]
@andreweick I notice you have every branch deploying on Netlify which means for every commit on a PR we trigger two builds, on for the PR and one for the Branch. Our builds are heavier than usual due to the photo pre-build plugins.

I would limit branch deployment to production and Deploy Preview and maybe one or two branches if the need emerges (staging, etc...)

My own 2 🪙

**Comment by andreweick** [comment]
@regisphilibert thanks -- good catch -- updated to only build/deploy main
