### ISSUE TITLE
Migrate from imgix to CLOUDFLARE images (Responsive Images)

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#157]
With imgix current price increase, and in order to reduce my services, I'd like to migrate to [cloudflare images](https://developers.cloudflare.com/images/cloudflare-images/serve-images)

Not knowing anything, I created these sizes for responsive images

* 1280w (1280x1280)
* 1920w (1920x1920)
* 2560w (2560x2560)
* 320w (320x32)
* 640w (640x640)
* 960w (960x960)
* public (1368x768)
* square150 (150x150)
* squarethumb (100x100)

I'd like to add a shortcode to display the image from  Cloudflare, and (maybe?) modify the image markdown link to emit a responsive CLOUDFLARE image rather than a IMGIX link..

**Comment by regisphilibert** [comment]
We could use the current system in place but there's one problem. Cloudflare images URL do not mention the filename, just he ID (maybe it's something you can change.

Currently if we find this in the markdown:
```
![McLean Girls Soccer](/20210522-soccer-0001.jpg)
```
We grab the destination and turn it into an imgix URL: `https://edc.imgix.net/20210522-soccer-0001.jpg?auto=format&ch=Width,DPR&q=95&w=480`

Problem is CloudFlaire would store this image under its ID at `https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/000b6b49-c71e-412c-5222-a20e37883b00/public`

Do you have any control over the permalink structure of images with the cloudflare solution?

**Comment by regisphilibert** [comment]
In the mean time we can create a shortcode like this:

```
{{< figure_cloudflare src="000b6b49-c71e-412c-5222-a20e37883b00" title="Lady" >}}
```

**Comment by andreweick** [comment]
@regisphilibert good catch. 

Hmm,  I hadn't considered that case (I was thinking about the 9000K images).

Two things I can think of 
1. I can write a function (cloudflare worker) that will given a name return the Cloudflare UID
2. I can manually update the markdown files to use UID's rather than names with the new shortcode

I think it would be "cleaner" for me to manually edit the markdown files, but that's not a user friendly for the editor and as you said in the other issue the URL's aren't as pretty (which is a real drag)

If I did write a functioned that given a filename returned a UID, can you see how that would work?  Would that be logic you add to the short code that gets the file name on build?

**Comment by regisphilibert** [comment]
> If I did write a functioned that given a filename returned a UID, can you see how that would work? Would that be logic you add to the short code that gets the file name on build?

It does mean the build would call your endpoints each time the shortcode is invoked. Or if you implement the endpoints i'm dicussing [here](https://github.com/andreweick/eick.com/issues/156#issuecomment-993685647), then Hugo will fetch it once per build, and use it whenever to pair images with their ID/filename
