### ISSUE TITLE
offline hugo build full site (migrate away from ondemand builders?)

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#160]
I'd like to make the offline hugo build create *all* the pages (even the 'just in time pages', all 10,000 or so of them.  I think either have the build have two NPM build commands (one for netlify that does just in time building and one for offline?) or is there someway to tell when the site is being built in netlify?

I'm trying to consolidate my services (and simplify the process!) and want to migrate from Netlify to cloudflare  Cloudflare doesn't have the idea of "on demand builders" so I want to see how long it takes to "just build" the site.

**Comment by regisphilibert** [comment]
@andreweick My answer is [here](https://github.com/andreweick/eick.com/issues/156):
