### ISSUE TITLE
Migrate from Mux Video to Cloudflare streams

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#161]
**N.B.** ~~Still working on setting up a sample file,~~ but it looks like it works like the others

In order to consolidate my services, I want to migrate from MUX video into Cloudflare streams.

[API docs](https://api.cloudflare.com/#stream-videos-list-videos)

### [Play video:](https://api.cloudflare.com/#stream-videos-embed-code-html)
I actually don't understand this at all -- but I suppose once you have the signed URL from above, you can embed at like the [sample at](https://developers.cloudflare.com/stream/viewing-videos/using-the-player-api).

For testing, video ID is 995f4df59ab4ae90e5a2c1af8e829988 public and doesn't need to be signed

Please extend the shortcode to be able to set the animated gif thumbnail as [detailed here](https://developers.cloudflare.com/stream/viewing-videos/displaying-thumbnails#use-case-3-generating-animated-thumbnails)

Example: https://videodelivery.net/995f4df59ab4ae90e5a2c1af8e829988/thumbnails/thumbnail.gif?time=38s&height=600&duration=4s

The player is talked about [here](https://developers.cloudflare.com/stream/viewing-videos/using-the-player-api) so I think these are the parameters in the shortcode?

I know 5 videos isn't a good test, but I'll try and upload more...

Same as with the "photos" page, I'd like to have a "thumbnail" type page with all the view all the videos, then expand to a page that shows a 1 video per page, and also a shortcode that will show the video in a page

**Comment by andreweick** [comment]
Ok, all the above (except "Play Video") is old now

I've added a method to return a JSON similar to what you suggested in the #156.

To get a JSON list of videos

```bash
curl http://edc-router.missionfocus.workers.dev/streamList/minimal | jq
```

```json
[
  {
    "date": "2021-12-05T17:24:56.918275Z",
    "videoid": "995f4df59ab4ae90e5a2c1af8e829988",
    "filename": "2021-11-26 Libby Jury",
    "url": "https://iframe.videodelivery.net/995f4df59ab4ae90e5a2c1af8e829988",
    "requireSignedURLs": false,
    "height": 3840,
    "width": 2160
  },
  {
    "date": "2021-12-05T17:24:25.97991Z",
    "videoid": "55e6c01294ede8dfb538d5252aafb189",
    "filename": "2021-08-22 Libby Schubert Recital",
    "url": "https://iframe.videodelivery.net/55e6c01294ede8dfb538d5252aafb189",
    "requireSignedURLs": true,
    "height": 1080,
    "width": 1920
  },
  {
    "date": "2021-12-05T17:23:48.699531Z",
    "videoid": "f5f0af3bd95d168f6435faf999f3d886",
    "filename": "2021-02-28 Libby Recital",
    "url": "https://iframe.videodelivery.net/f5f0af3bd95d168f6435faf999f3d886",
    "requireSignedURLs": true,
    "height": 2160,
    "width": 3840
  }
]
```

To sign the URL:

```bash
curl http://edc-router.missionfocus.workers.dev/signUrl/f5f0af3bd95d168f6435faf999f3d886 | jq
```

```json
{
  "uid": "f5f0af3bd95d168f6435faf999f3d886",
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIn0.eyJzdWIiOiJmNWYwYWYzYmQ5NWQxNjhmNjQzNWZhZjk5OWYzZDg4NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIiwiZXhwIjoiMTYzOTk0NjM1OCIsIm5iZiI6IjE2Mzk5MzkxNTgifQ.V95O2ypz9fGbRy4EhQQZ2CvQjQ_l-s5m129Nwic3_ZviiIpiDfxxDh7ghfe1sf3w-6LJAcAljm7ojyS56A3a8ZeNAbfoZLn9l0HCoJzx2kwGw1LsRODwwLR4BXDFpPCALsF1zBLgDATmLS87-LLEZfXSw9yuHXItrdPVGtcbjtCIxGyiDBa7bNEdS0-RqkceOwAIBI8xLR5mNfggR5KgQlRsRVZMd-pqRAukMKUq3YisZSjMbblFJIaP1VjTgKI5Y-6wO3BurhPxhVHx5aWtxOZQ40w1wYwVyoDULZ8LK2yUhFkwA1_eA5ax72c9QnKxpp66XipgbCyof4BaiDD1gA",
  "signedUrl": "https://iframe.videodelivery.net/eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIn0.eyJzdWIiOiJmNWYwYWYzYmQ5NWQxNjhmNjQzNWZhZjk5OWYzZDg4NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIiwiZXhwIjoiMTYzOTk0NjM1OCIsIm5iZiI6IjE2Mzk5MzkxNTgifQ.V95O2ypz9fGbRy4EhQQZ2CvQjQ_l-s5m129Nwic3_ZviiIpiDfxxDh7ghfe1sf3w-6LJAcAljm7ojyS56A3a8ZeNAbfoZLn9l0HCoJzx2kwGw1LsRODwwLR4BXDFpPCALsF1zBLgDATmLS87-LLEZfXSw9yuHXItrdPVGtcbjtCIxGyiDBa7bNEdS0-RqkceOwAIBI8xLR5mNfggR5KgQlRsRVZMd-pqRAukMKUq3YisZSjMbblFJIaP1VjTgKI5Y-6wO3BurhPxhVHx5aWtxOZQ40w1wYwVyoDULZ8LK2yUhFkwA1_eA5ax72c9QnKxpp66XipgbCyof4BaiDD1gA"
}

```

**Comment by andreweick** [comment]
It seems like [this player](https://developers.cloudflare.com/stream/viewing-videos/using-the-stream-player) is different in that it (can) return an embed that contains the player ... does that make it easier or harder to work with (or just different)?

**Comment by regisphilibert** [comment]
My brain is a bit rusted on this signedURL things.

But I feel like we could be using a client side call for this endpoint (if you block access from outside of eick.com rather than relying on a serverless functions.

Problem is when I try that I get this error:

```
Access to fetch at 'http://edc-router.missionfocus.workers.dev/signUrl/995f4df59ab4ae90e5a2c1af8e829988' from origin 'http://localhost:1313' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

Do you have any CORS already set?

**Comment by andreweick** [comment]
Goodness -- ok I'm not sure I know what a CORS is -- This is the function (don't laugh, I learned javascript this weekend).  I had thought the Header Control would open it up?

But, you are right, a client call would also work.  https://developers.cloudflare.com/stream/viewing-videos/securing-your-stream#option-1-using-the-token-endpoint, but then you'd have to have the bearer token, no?

(N.B., the bearer token is in netlify variables...)

```javascript
async function signUrl(params) {

    var tokenJson = {};

    let headers = new Headers({
		'Access-Control-Allow-Origin': '*',
		'Access-Control-Allow-Methods': 'GET, HEAD, POST, OPTIONS',
		'Access-Control-Allow-Headers': '*'
	});

    var resp = await fetch('https://api.cloudflare.com/client/v4/accounts/' + CLOUDFLARE_ACCOUNT_ID + '/stream/' + params + '/token', {
        method: "POST",
        headers: {
            'Authorization': 'Bearer ' + STREAM_API_KEY
        }
    });

    var data = await resp.json();

    console.log ('token success? ' + data.success)
    if (data.success == true) {
        tokenJson['uid'] = params
        tokenJson['token'] = data.result.token
        tokenJson['signedUrl'] = 'https://iframe.videodelivery.net/' + data.result.token
    }


    return new Response(JSON.stringify(tokenJson), {
        status: 200,
        headers: headers
    });
}

```

**Comment by andreweick** [comment]
That being said, it's easy enough to store a variable somewhere so the client can call the "/token" api directly

**Comment by regisphilibert** [comment]
I added a shortcode `cloudflare_video`. It builds an iframe, with enforced (it seems) height and width. Maybe we should discuss the best width/height, and allow to overwrite those defaults?

**Comment by regisphilibert** [comment]
Let's move back this sign url conversation to #164
