### ISSUE TITLE
Pager bar on the "Home" screen

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#162]
Not sure if I am mis remembering, but was there a pager bar on the home screen to go through the posts?

**Comment by andreweick** [comment]
Might be solved by #167 ?

**Comment by regisphilibert** [comment]
@andreweick reading this makes me realize #167 does not only concern the pages listing entries of a given tag, but all list pages?

**Comment by andreweick** [comment]
yes? 

Or I suppose more accurately, i think we tried to multi column early, but I think going single column with a pager bar makes more sense

**Comment by regisphilibert** [comment]
That was a quick one @andreweick. You can see it here: https://deploy-preview-173--www-eick-com.netlify.app/

**Comment by andreweick** [comment]
That was fast @regisphilibert -- I think the pager bar has jacked up the formating on the "portrait" iphone screen?

Also the "photo grid" on the portrait iphone is a bit off?

**Comment by regisphilibert** [comment]
thanks for the catch! I'll address

**Comment by regisphilibert** [comment]
All good now @andreweick 👌
