### ISSUE TITLE
Signed URLs for private content.

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#164]
Both Streams (video) and Images use Signed URLs to show private content.  I haven't written the endpoint to return a signed URL, but would like to leave a "hole" in the logic to call it.

Check if signed URLs only work for private content or for all content (e.g. do you need a conditional to check if URL signing is needed)

**Comment by andreweick** [comment]
I've added a method that signs the URL without having to mess with authentication on the front end --

```bash
curl http://edc-router.missionfocus.workers.dev/signUrl/f7ff2984b41d06688b64f0b0730e59ca | jq
```

returns

```json
{
  "uid": "f7ff2984b41d06688b64f0b0730e59ca",
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIn0.eyJzdWIiOiJmN2ZmMjk4NGI0MWQwNjY4OGI2NGYwYjA3MzBlNTljYSIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIiwiZXhwIjoiMTYzOTk0NTU3NiIsIm5iZiI6IjE2Mzk5MzgzNzYifQ.CGqEymTXD-1_s0eqUxs0d74YOTkCuer7OEVWuhf2QzoIPDKoE5v1o3UVUgDCLJWy9kgDiMVWPrr4SoWYeq9SrxAZsZZaanp2x3DpvungxZMMJaW3W2giR9r7aMj6iaZa-sfWKxP05OOOIb9OoVNV1iNaIBVP_8P-Y-770pBEnvXwpvl-VSDzBiqrwMer1stYhwGi-bzrnqLnyciomhdL4YfFtdRXTGcpyMQ_yMw0mlRtrn1gcH8ZpYj_T_Wqw4Zw3KhebUDHJQJSxtz9itnrErfYx8hQm1jlI_sdMiGoWw64OTD-vo9Nd1CBaEX7Nx55HGHbvooHd8IYK-5zZE5YYw",
  "signedUrl": "https://iframe.videodelivery.net/eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIn0.eyJzdWIiOiJmN2ZmMjk4NGI0MWQwNjY4OGI2NGYwYjA3MzBlNTljYSIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIiwiZXhwIjoiMTYzOTk0NTU3NiIsIm5iZiI6IjE2Mzk5MzgzNzYifQ.CGqEymTXD-1_s0eqUxs0d74YOTkCuer7OEVWuhf2QzoIPDKoE5v1o3UVUgDCLJWy9kgDiMVWPrr4SoWYeq9SrxAZsZZaanp2x3DpvungxZMMJaW3W2giR9r7aMj6iaZa-sfWKxP05OOOIb9OoVNV1iNaIBVP_8P-Y-770pBEnvXwpvl-VSDzBiqrwMer1stYhwGi-bzrnqLnyciomhdL4YfFtdRXTGcpyMQ_yMw0mlRtrn1gcH8ZpYj_T_Wqw4Zw3KhebUDHJQJSxtz9itnrErfYx8hQm1jlI_sdMiGoWw64OTD-vo9Nd1CBaEX7Nx55HGHbvooHd8IYK-5zZE5YYw"
}
```

I've tested this with the video Signed URLs, still working on the images signing -- my idea is that the "full single picture" will require signed URL's but the thumbnails won't

**Comment by regisphilibert** [comment]
We could discuss using Hugo to fetch the signURL himself. But I'm not sure how often those URL are refreshed, but you would have to rebuild your site to keep them synched.

For now:
I bypassed the CORS issue by wrapping the signed data fetching inside a serverless function which the client will call.

Client cannot obfuscate anything, this will always be surfaced somewhere so we don't want your token in there. 
By using serverless we ensure we can use a token later and we bypass CORS because the endpoint (/.netlify/functions/sign-media?id=xxxx) is on the same domain. Downside is, anybody finding the serverless function URL can get a signURL, but again, they at least won't be able to retrieve your token.

For now we have a shortcode discussed in #161 which take an id and an optional boolean for private. 

If it's private, then we do not add the `src` attribute with Hugo (in html), we fetch the sign media endpoint, and use the retrieved `signURL` to add set the `src` attribute with javascript.

You can see it in action on https://deploy-preview-173--www-eick-com.netlify.app/media-test/ (scroll down to the private video)

**Comment by andreweick** [comment]
@regisphilibert awesome -- I'll have to look at how you did it -- Cloudflare has a very similar strategy as netlify (put a well-named file in the ~/functions directory and it will be serverless) so it should be easy to migrate from netlify to cloudflare when your'e done.

Would the same technique work for private images?  https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/a6bf2a66-2ffe-4217-1fc0-31f64276b600/w960signed should be blured until the URL is signed by a function.  I'm worried we may need a similar function (it seems to be a different function to sign a stream vs an image (https://developers.cloudflare.com/images/cloudflare-images/serve-images/serve-private-images-using-signed-url-tokens)

![signed](https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/a6bf2a66-2ffe-4217-1fc0-31f64276b600/w960signed)

**Comment by regisphilibert** [comment]
hi @andreweick getting back into it. 

So for images I guess we can have the same solution yes, but I've tried passing the one above in your `http://edc-router.missionfocus.workers.dev/signUrl` endpoint and nothing is returned.

**Comment by regisphilibert** [comment]
So we already have a shortcode for cloudflare_image. But it creates a responsive figure with several media (per screen):

```html
<figure class="max-w-full">
  <picture>
    <source data-srcset="https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/000b6b49-c71e-412c-5222-a20e37883b00/w960" media="(min-width: 768px)" srcset="https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/000b6b49-c71e-412c-5222-a20e37883b00/w960">
    <source data-srcset="https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/000b6b49-c71e-412c-5222-a20e37883b00/w640" media="(min-width: 480px)" srcset="https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/000b6b49-c71e-412c-5222-a20e37883b00/w640">
    <img class=" lazyloaded" src="https://imagedelivery.net/Zgety72ez9NMy5vNjlIElg/000b6b49-c71e-412c-5222-a20e37883b00/w320" title="Lady">
  </picture>
  <figcaption>
     <p>Lady</p>
  </figcaption>
</figure>
```

We could add a new parameter to the shortcode to indicate that the image is `signed` and then add an attribute to the figure so client JS knows to fetch the signed URL and replace the figure's src attribute once found.

**Comment by andreweick** [comment]
Hi @regisphilibert -- happy new year.  Great minds think alike, was going to ping you to level set.  I've lost track of which strategy you are working -- 

Let me double check the routes I created and ensure they are all in working order

**Comment by andreweick** [comment]
@regisphilibert Sorry, I let the Token expire on that function -- fixed now

## Streams
Ok, I updated the endpoints a bit --

### SignStreamUrl 
returns just the URL

curl https://edc-router.missionfocus.workers.dev/signStreamUrl/809c28521fea51dea22ff94a44c32135

returns
https://iframe.videodelivery.net/eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIn0.eyJzdWIiOiI4MDljMjg1MjFmZWE1MWRlYTIyZmY5NGE0NGMzMjEzNSIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIiwiZXhwIjoiMTY0MTY4MDc0NyIsIm5iZiI6IjE2NDE2NzM1NDcifQ.NzsOr67XflZRieyw2_CGq5Pv0cbyEAgKjF6WkD7J3gS2bUlRKMJThVeZW_BdOAFOt0kUd_WwFCc7il6Z8JxYkLBq6HgwMqKSWI_HXnP9LEX0wW73EhnO1vsbi7lMJVQpUUWC-QCiqtZgRr322v_668GgXd7x_LyZSy_T1Uu0ilIo_82nHSpYi7aieYZPt_B3n9rFSorpjDsIwqdqpofsIzI22w-kS0D20WdcGFtPNmE-mQoUtVrtIemSdnweshZP0NgkigYmHWXHfXzZOKeB0X7BPzN65MbEgw3mcktqYvfDKLzr4YSNW3ttqDlU_brtc8Jee2SEmz-E3pfT-H3Nyg

### SignStreamJson 
Returns a Json structure containing the URL

curl https://edc-router.missionfocus.workers.dev/signStreamJson/809c28521fea51dea22ff94a44c32135

returns

{
  "uid": "809c28521fea51dea22ff94a44c32135",
  "success": true,
  "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIn0.eyJzdWIiOiI4MDljMjg1MjFmZWE1MWRlYTIyZmY5NGE0NGMzMjEzNSIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIiwiZXhwIjoiMTY0MTY4MDk0MyIsIm5iZiI6IjE2NDE2NzM3NDMifQ.leBZeAS6Uyz1RHr2JQBUa55RQyLkW1qbhqFV6m3F5rB1m_m5mpivpFMBqsr7N4awYMFW-Y9VmRDC1bJmCt_46pWczG9Pwq4d7Y4at7_g7bs5MDywslQYEoOGq2O5XG-yKwzoLmaAnzz-BRPQpX1N7bJhJgIjA5mFO_Fooi1emj2VqT0tHQvnZuS0yw1AOk8Q18TQOtM2nb-ZhC0XSuhEfQCOdyc7xAhINHEI7-ufp9tT6Pra3VPfNt0TC-YH_MoHL4AcfC4hNdxmv8oTiIxw46jaNZkdQMJORpIXY2IOyc51LJerUpZMHkJWjPch0N43upwvtGJYn9rPnblxMtoWug",
  "signedUrl": "https://iframe.videodelivery.net/eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIn0.eyJzdWIiOiI4MDljMjg1MjFmZWE1MWRlYTIyZmY5NGE0NGMzMjEzNSIsImtpZCI6IjYxMGRmM2M5YzE3MTVhMzJiMDNlOTI0MTg2MmMxZWZmIiwiZXhwIjoiMTY0MTY4MDk0MyIsIm5iZiI6IjE2NDE2NzM3NDMifQ.leBZeAS6Uyz1RHr2JQBUa55RQyLkW1qbhqFV6m3F5rB1m_m5mpivpFMBqsr7N4awYMFW-Y9VmRDC1bJmCt_46pWczG9Pwq4d7Y4at7_g7bs5MDywslQYEoOGq2O5XG-yKwzoLmaAnzz-BRPQpX1N7bJhJgIjA5mFO_Fooi1emj2VqT0tHQvnZuS0yw1AOk8Q18TQOtM2nb-ZhC0XSuhEfQCOdyc7xAhINHEI7-ufp9tT6Pra3VPfNt0TC-YH_MoHL4AcfC4hNdxmv8oTiIxw46jaNZkdQMJORpIXY2IOyc51LJerUpZMHkJWjPch0N43upwvtGJYn9rPnblxMtoWug"
}


### Image Signed Url
Let's leave thee short code as it is --- If I need the signedUrl I'll come back to it in a later sprint...

### CORS issues?
I think you said a while ago there was CORS (or some type of URL error) using the endpoints?  Can you set up a test on media-test.md page and I can debug? 

### Other functions from the routes
I think you said a while back that you aren't using the other endpoints, right?  Your'e getting the list of images && streams right from the cloudflare API? 

Could you PR the cloudflare_image shortcode?  I'll try it out :-)

### Netlify?
Are you (currently) using any netlify functions?  I can work on migrating those functions to cloudflare functions

**Comment by regisphilibert** [comment]
Ok @andreweick I've updated the endpoint in the severless function.

## CORS Issues

The cors issues are not more as I decided to rely on a serverless function to fetch your endpoint. This means the client on needs that serverless function (as its own endpoint is relative to the domain `/.netlify/functions/signed-media`), we cannot run into CORS problems anymore.

## Other functions from the routes

After this branch is merged we'll be relying on the following serverless functions:

- [/functions/assetid2infos.js](https://github.com/andreweick/eick.com/blob/156-cloudflare-images/functions/assetid2info.js): this is for mux.
- [/functions/sign-video-url.js](https://github.com/andreweick/eick.com/blob/156-cloudflare-images/functions/sign-video-url.js): this is for mux private videos
- [/functions/sign-media.js](https://github.com/andreweick/eick.com/blob/156-cloudflare-images/functions/sign-media.js): this is for cloudflare private videos.
- [/functions/deploy-succeeded.js](https://github.com/andreweick/eick.com/blob/156-cloudflare-images/functions/deploy-succeeded.js): this is what netlify runs after every successful build. For now it only takes care of the meili search index update.

**Comment by andreweick** [comment]
@regisphilibert great -- just take off the [DO NOT MERGE] when ready to merge.

Also, you can delete the Mux video, -- i'll move those videos over to CF (hopefully that will simplyfiy the code)

**Comment by andreweick** [comment]
@regisphilibert could you do a PR with just the cloudflare_image?  (or is it tied into the full PR)?

**Comment by regisphilibert** [comment]
It's all tied in in the same PR I'm afraid. Everything was kind of interconnected. What part of the cloudflare implementation do you imply with `cloudflare_image`?

**Comment by regisphilibert** [comment]
> Also, you can delete the Mux video, -- i'll move those videos over to CF (hopefully that will simplyfiy the code)

I'd rather we merge this first (as you have a couple of mux shortcodes in there. Wait fo you to replace them with the cloudflare solution and then I'll delete everything MUX form the repo.

What do you think?

**Comment by andreweick** [comment]
> > Also, you can delete the Mux video, -- i'll move those videos over to CF (hopefully that will simplyfiy the code)
> 
> I'd rather we merge this first (as you have a couple of mux shortcodes in there. Wait fo you to replace them with the cloudflare solution and then I'll delete everything MUX form the repo.
> 
> What do you think?

Agree all -- I was just thinking this morning that NETLIFY_CMS might be a casualty of the move to CF_PAGES as well ☹️  -- but I've started using VSCODE again anyway, so...
