### ISSUE TITLE
Sprint 5 cleanup

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#184]
@regisphilibert 

Working on the site this weekend -- a few niggles:

1. The private Cloudflare Video doesn't work.  I made a [test page](https://61f5bdb1eeebf30008cb3029--www-eick-com.netlify.app/video-test/).  I'm working on the migration to CF Pages, so I'll leave the netlify address in the issue.  This might be OBE by the time you see this if I finish the migration
2. Search seems to have disappeared?

**Comment by regisphilibert** [comment]
Hi @andreweick sorry for the delay. I'm working on those today and will get back to you!

**Comment by regisphilibert** [comment]
1. you updated node-fetch to > 3? Do you need this version explicitly need this version? It seems that since 3. the module cannot be imported using `const require('node-fetch') ` which is used in the `signe-media` serverless function.
I've read you can add `"type"= "module"` to the package json in order to fix that, but I'm afraid this might break other behaviour on the site. Hence my question, if you don't need node-fetch 3, then I'll just downgrade it back to 2.6.

**Comment by regisphilibert** [comment]
2. Also instant-meilisearch has been downgraded from `0.5.1` to `0.2.1` thus breaking the scripts. 

Conclusion this is all fixable with using the proper npm modules version of `node-fetch` and `instant-meilisearch`. I'm pretty sure I could upgrade meilisearch safelyl but just in case can you confirm this not going to interfere with other area of the site?

Thanks @andreweick

**Comment by regisphilibert** [comment]
Looking at this today, the search is fixed, but now the serverless function url gives a 404... https://www.eick.com/.netlify/functions/sign-media/?id=809c28521fea51dea22ff94a44c32135

I can't explain why, is there anything that comes to mind? If not, I'll investigate further...

**Comment by andreweick** [comment]
@regisphilibert the DNS must have updated over to cloudflare pages :-) -- I bet it would work if "hardcoded" the page to be the Netlify fuction name (https://6203d088820fe354e6ad0334--www-eick-com.netlify.app/) ".functions/name-js" ?  ALthough that would probably be CORS

I'll work on getting the function back returning something on cloudflare functions and ping you if I can't make any headway

**Comment by regisphilibert** [comment]
Awesome! Thanks!
