### ISSUE TITLE
Upgrade code

### ISSUE THREAD

**Issue by regisphilibert** [andreweick/eick.com#76]
- use most of the tools from https://github.com/theNewDynamic/hugo-project-template
- Use Tailwind 2

**Comment by andreweick** [comment]
@regisphilibert https://www-eick-com.netlify.app

**Comment by regisphilibert** [comment]
@andreweick could I ask you to add me (`login@regisphilibert.com`) to your Netlify instance so I can do the switch for you. Otherwise we'll have to coordinate a time.

**Comment by andreweick** [comment]
@regisphilibert I'm off to a meeting downtown -- can I just make the switch right now?  I don't mind if it's broken while you work

Switch to witch branch?

**Comment by regisphilibert** [comment]
Netlify: Switch to `main`.
Github: Set `main` as default branch. 

Then on your local, don't forget to switch to `main`.

**Comment by andreweick** [comment]
Thanks -- just switched Netlify, will with GH when I get back tonight

(Also triggered deploy on netlify, so should be going through)

**Comment by andreweick** [comment]
@regisphilibert is there anything I need to do for netlify CMS wrt switching branches -- I have a few "drafts" -- should I just move those PRs over to "main" branch?

**Comment by regisphilibert** [comment]
Good question. I would guess so. I just updated the settings of the CMS to follow the `main` branch. (Doc says it defaults to master, we never had the case as we're always using `main`). But I don't think it will affect the generated PRs.

I think you can edit the branch it is based on to `main`. The code upgrade did not change the location of your content dir, so I don't see any reason why this would create issues. Now I'm not sure how NetlifyCMS will respond but it's worth trying. If you stumble on anything weird, just let me know and we could just add this content manually.

Let me know how it goes.

**Comment by andreweick** [comment]
thx -- if it's a problem I can clipboard version control it over---

**Comment by andreweick** [comment]
/ close? (I'm done)
