### ISSUE TITLE
Implement Photo section from remote S3 Bucket.

### ISSUE THREAD

**Issue by regisphilibert** [andreweick/eick.com#77]
We should create a pre-build plugin for Netlify which will perform the API requests on all images present in the json file and create markdown files for Hugo to consume.

**Comment by regisphilibert** [comment]
@andreweick

#### i#mgix/amazon
Are the images already on imgix, this for example: `https://mfc.imgix.net/15_reps_of_groups_for_swedish_flag_day_skansen_june_6_65.jpg` is not working, maybe I've got the wrong imgix domain.

If not on imgix, what would be their public URL from Amazon?

#### Metadata (no rush)

Do you have any idea which and how metadata should be represented on the site? This is what the API gives me for any given photo:

```json
{
  "Name": "10_eicks_pose_by_monolith_.jpg",
  "ParsedName": "10 eicks pose by monolith .jpg",
  "Artist": "Harry Eick",
  "CaptureTime": "1965-12-31T14:45:47Z",
  "Description": "",
  "Caption": "",
  "ID": 15364677497137926000,
  "Height": 0,
  "Width": 0,
  "Classification": {
    "Labels": [
      {
        "Name": "Monument",
        "Confidence": 99.91818237304688
      },
      {
        "Name": "Architecture",
        "Confidence": 99.40982055664062
      },
      {
        "Name": "Building",
        "Confidence": 99.40982055664062
      },
      {
        "Name": "Person",
        "Confidence": 98.69864654541016
      },
      {
        "Name": "Human",
        "Confidence": 98.69864654541016
      },
      {
        "Name": "Pillar",
        "Confidence": 93.5531005859375
      },
      {
        "Name": "Column",
        "Confidence": 93.5531005859375
      },
      {
        "Name": "Elephant",
        "Confidence": 93.26807403564453
      },
      {
        "Name": "Animal",
        "Confidence": 93.26807403564453
      },
      {
        "Name": "Mammal",
        "Confidence": 93.26807403564453
      },
      {
        "Name": "Wildlife",
        "Confidence": 93.26807403564453
      },
      {
        "Name": "Obelisk",
        "Confidence": 92.588134765625
      }
    ]
  }
}
```

**Comment by andreweick** [comment]
@regisphilibert 

I'd say parsed name as the "alt" tag, Captured Time, Title, Description underneath the image.

I'd like the URL to be the "https:/ .... / photo / NAME" or ""https:/ .... / photo / ID"

I was thinking the "Classification | NAME" to be the (tags).

Yes, they are loaded into IMGIX at:

https://edc.imgix.net/15_reps_of_groups_for_swedish_flag_day_skansen_june_6_65.jpg


**edc**.imgix.net not *mfc*.imgix.net

**Comment by regisphilibert** [comment]
@andreweick there is a [PR](https://github.com/andreweick/eick.com/pull/80) for this. It's tracking the following branch https://github.com/andreweick/eick.com/tree/add-photos

I wonder if you could add the branch to your netlify instance so we can test it and see the results at `add-photos--www-eick-com.netlify.app` but the easiest would be for you to add me to your Netlify as other settings update might be required.

### Status

For now I'm only able to fetch as many as 2600 images and therefor create pages for them.
1. I'm setting a limit to 3000 fetches, because above that I end up with either an error `  FetchError: request to https://b2e2t0ibm9.execute-api.us-east-1.amazonaws.com/Prod/p..., reason: read ECONNRESET` or an ever stopping script.
2. It seems many filenames (a bit less then 400 out of the first 3000) listed in the datafile are responding with empty data:
```
{
    "Name": "",
    "ParsedName": "",
    "Artist": "",
    "CaptureTime": "0001-01-01T00:00:00Z",
    ...
}
```
Which I'm pretty sure means they do not exist on the bucket.

I think the next step is to be able to fetch the list of images available on the bucket but i'm not sure where to look.

In any case, that's where we're at.

**Comment by andreweick** [comment]
@regisphilibert Can you email the email I should use to add you to the team?

1.  Huh, that must be an error.  I didn't think at all about that (I assumed scale wouldn't be a problem). I didn't see anything abnormal in the logs, but I must have some limit in there that I am hitting
2. Must be related to ☝️ -- the Name is a primary key, so can't be blank in DynamoDB -- it must be my retrieval code

**Comment by regisphilibert** [comment]
@andreweick I tried and upped the number of image to retrieve from the API to 5000 and Netlify chocked. I think we're putting a lot of stress on the API. I guess what would be ideal is to use an S3 API Node library which knows how to handle the calls for it's APi.

In the mean time we can try and merge this with 3000 limts, but I can't garantee Netlify is not going to choke sometime and as this will now be invoked on every build of the site... this could create issues.

**Comment by andreweick** [comment]
@regisphilibert oh yes, I'm sure it's a bug in my server code 👍 -- AWS makes some things so painful!  I will have to look at it and next time @budparr can carve off some time for me we will address the "beyond 3000 images" issue.  (if you know of a Node API library I'll re-write mine to do that....)

Is this a case where https://docs.netlify.com/configure-builds/on-demand-builders/?_ga=2.205082259.282903018.1622496295-1987282647.1618689379 would work though?

**Comment by regisphilibert** [comment]
We could evaluate the value of on demand builder for the use case but it would take time.

**Comment by andreweick** [comment]
Yes, it seems this is the use case for on demand builder., but we can evaluate in the next sprint if we've run out of time.  I made #93 so we can close this issue when you are ready.

I'll work with @budparr on scheduling next sprint
