### ISSUE TITLE
Netlify CMS niggles

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#79]
Niggles when I use [Netlify CMS](https://www.eick.com/cms)

1. Missing image
2. Preview link doesn't work
![Screen Shot 2021-05-19 at 9 14 10 AM](https://user-images.githubusercontent.com/1289435/118818823-ba8d1700-b882-11eb-8c4f-96637190f099.png)

![cms-missing-image-1](https://user-images.githubusercontent.com/1289435/118818522-6a15b980-b882-11eb-9374-82205875fea1.png)

**Comment by regisphilibert** [comment]
1. @andreweick unfortunately the image issue is upstrea: https://github.com/netlify/netlify-cms/issues/5411
2. I cannot access the CMS in production and therefor could not verify my fix but I'm confident this (https://github.com/andreweick/eick.com/commit/8ed1212094f48358cdc075d12aa67c1d2e9c0adf) should do it.
3. There was no 3 right?

**Comment by andreweick** [comment]
@regisphilibert goodness -- ok, it's been so long since there was a "it works only in this one browser" type bug I didn't think to try a different browser -- I'll do that.  Jeepers -- next thing you know I'll have to load IE...

**Comment by andreweick** [comment]
@regisphilibert The "Preview" link still doesn't work -- I sent a "reset password" link to your user login@regisphilibert.com which should get you into the CMS

**Comment by andreweick** [comment]
@regisphilibert If it helps, the "View Preview launches 

https://deploy-preview-87--www-eick-com.netlify.app/article/2021-05-23-mclean-girls-soccer

and the real is located at:

https://deploy-preview-87--www-eick-com.netlify.app/posts/2021-05-23-mclean-girls-soccer/

So it seems changing "/articles/" to "/posts/" will do it...

**Comment by regisphilibert** [comment]
I see, just fixed, I think :)

Let me know how it goes.
