### ISSUE TITLE
Add search to site

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#81]
Trying to use search engine https://www.meilisearch.com as you suggested @budparr -- it was pretty easy to set up

I setup the service on the endpoint (https://search.eick.ws).  I set the MEILI_MASTER_KEY in Netlify and will email it to you.

It looks like you populate it by pushing a JSON file and then hook up a search box on the website.

**Comment by regisphilibert** [comment]
@andreweick I set a basic search on production using Meili and InstantSearch (wrapped in TND Search Module). I don't know if you're familiar with Algolia's InstantSearch but it's a rich component library open sourced that can also wok with Meili as a host. 

If you check the params file here: https://github.com/andreweick/eick.com/blob/5fa573d34c5359e957987eb93edc44ecf1597ca0/config/_default/params.yaml#L101-L150

You'll find we made pretty easy to customize the front.

In the mean time you can see it in action on https://www.eick.com/search/

**Comment by andreweick** [comment]
@regisphilibert ok, wow, that is flexible.  I need to study it.  I'm glad you were able to extend TND_search. also -- setting up Meili was (very literally) click easy.

So there isn't a crawler, but your are pushing JSON objects to populate?  Could you push "all the photographs" also?

**Comment by regisphilibert** [comment]
> So there isn't a crawler, but your are pushing JSON objects to populate

It's a basic [node script](https://github.com/andreweick/eick.com/blob/main/functions/deploy-succeeded.js) served through Netlify function, they have a filenaming UX so be calling `deploy-succeeded.js` Netlify knows to call the function after each successful deploy.

TND Search builds the index to send here: https://www.eick.com/tnd_search_index.json/

**Comment by andreweick** [comment]
@regisphilibert so should TND search "auto-magically" populate "S3 photos" when it is merged into main?

**Comment by regisphilibert** [comment]
> @regisphilibert so should TND search "auto-magically" populate "S3 photos" when it is merged into main?

Yes, though I'll need to intervene to structure the data. (Add the tags etc...)

**Comment by andreweick** [comment]
🤙  -- it's a crime GitHub doesn't allow Shaka sign as an emoji

**Comment by andreweick** [comment]
@regisphilibert Did this get merged into main?  I don't see a "search box" on deployed?

**Comment by budparr** [comment]
I don't see the PR. Régis is out today. I'll follow up with him in the morning.

**Comment by andreweick** [comment]
@budparr thanks -- to much partying after that big soccer game for @regisphilibert

**Comment by regisphilibert** [comment]
Hi @andreweick this is merged and in place at https://www.eick.com/search/ only not surfaced in the menu.
