### ISSUE TITLE
IMGIX plugin

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#88]
@regisphilibert Is [this](https://github.com/theNewDynamic/hugo-module-tnd-imgix) configured on my site?  Do you still recommend using it (I'm guessing, since it is your plugin :-)

What is the short code I should use to add IMGIX pictures to my site?

**Comment by regisphilibert** [comment]
We are using a new module [TND Media](https://github.com/theNewDynamic/hugo-module-tnd-media), with it we can either use Imgix (it imports the imgix module) or Hugo's own image transformation solution.

> What is the short code I should use to add IMGIX pictures to my site?

The same one, there was a bug introduced in the code upgrade but I just fixed it.

Now I can see you're using the imgix URL in there, but with the module in place and the right domain set, you can use relative images if you want. This way if we change imgix domain or decide to stop using imix, you won't have to update your content files. 

If you decide to do this though, we'll have to add the transformation through code, through the figure shortcode.

Also, I can see you are using `mdc.imgix.net/edc` that subdirectory can included in the module's imgix domain setting or on a per image basics, depending.

https://github.com/andreweick/eick.com/blob/27d743b1ca23accf96c5a372f0a3b27fd334a0aa/config/_default/params.yaml#L45-L52

PS: There is an `edc.imgix.net` as well. Does this mean we'll have to use two different imgix domain on the site once the Photo S3 logic has been implemented?

**Comment by andreweick** [comment]
@regisphilibert ok, thanks -- I like that you implied that I did something on purpose (verse just trying to get it to work!)

Yes, I'd like to use TND_media (vice the hardcoded URL).

WRT the two buckets, no, there will only be one imgix bucket (per site) so no need for extra logic there.

So once the TND Media is setup what would the markup look like, and I wanted to include image https://edc.imgix.net/close_up_montreal_police_on_parade2.jpg, what would the markup look like to get a full image width image that scales with the browser (and device size)

(Bonus question, do I have to do something to enable responsive images or does the plugin do that) -- 

I

**Comment by regisphilibert** [comment]
There two possibility: 
1. We can update the figure shortcode to use the Media module and apply some sensible imgix transformation for the blog. This way you will only have to use a relative url for the image when invoking the shortcode.
2. We can hook on the markdown image renderer to apply the same things (but without the caption). So: `![Alt text](/image.jpg "Title attribute")` is turned into an image with the proper alt/title and imgix to boot.

**Comment by andreweick** [comment]
hmm, that's a good one, I'll defer to your expertise on which is "the way" (mandolirian gif).

I prefer the "more standard", but working in the CMS screen is also nice (pushing toward standard markdown.

I would (think?) that the short code gives more flexibility to use IMGIX parameters and features though....

**Comment by regisphilibert** [comment]
@andreweick could you give me an example of an image on edc.imgix.net which works? One which is at the root if possible. Thanks a ton!

**Comment by andreweick** [comment]
Does this image work?

https://edc.imgix.net/close_up_montreal_police_on_parade2.jpg

The only Montreal picture I could find

**Comment by andreweick** [comment]
Also here is the curl for the metadata

```bash
curl https://b2e2t0ibm9.execute-api.us-east-1.amazonaws.com/Prod/photoapi/list\?name\=close_up_montreal_police_on_parade2.jpg | jq
```

**Comment by regisphilibert** [comment]
@andreweick I updated `render-image` so that you can use markdown as much as the figure caption.

The example page is here: https://www.eick.com/media-test/

**Comment by andreweick** [comment]
@regisphilibert 

But what markup should I be using to add a image that scales with the device size -- e.g. when I view https://www.eick.com/media-test/ on iPad and iPhone it requires panning.

Is there markup I should use to say the image should be some percentage of the width (e.g. 100%, 50%, etc -- with the default being 100%)

<img width="1194" alt="iPad-resize" src="https://user-images.githubusercontent.com/1289435/120337385-42cadd80-c2c1-11eb-9571-1f691db24ba1.png">
![iPhone-Eick-com](https://user-images.githubusercontent.com/1289435/120337386-43637400-c2c1-11eb-8254-5d65c4f3b1d9.png)

**Comment by regisphilibert** [comment]
This can happen with the CSS or we could build a responsive picture elements. Something like: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#the_srcset_attribute

**Comment by andreweick** [comment]
Ok, now I understand, yes, building the responsive picture element is exactly what I was thinking.  So your thought is that when I use "normal"markup

```
{{</* figure src="/close_up_montreal_police_on_parade2.jpg" caption="Figure 1: Montreal" */>}}
```

It would emit picture / srcset correctly

I made issue #92 for this, but I expect  it will have to be next sprint. (up to @budparr on scheduling)
