### ISSUE TITLE
Hugo clean starup

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#91]
Leave the repo in a "NPM run clean" state, and then have an NPM command that bootstraps the environment

- [x] Download HUGO binary for correct OS and architecture
- [x] Initialize any needed runtime
- [x] bin/Hugo* mod clean
- [x] REPO=github.com/theNewDynamic/thenewdynamic.com npm run modinit. ??
- [x] NPM run modpack
- [x] NPM install
- [x] Update .gitignore to ignore *all* generated files

I was trying to use my ARM Ubuntu machine and it took me a minute to figure out that the Hugo executable in the REPO was for the Mac.

It seems the get-Hugo script is already leaning toward architecture independence.

**Comment by andreweick** [comment]
It seems https://zwbetz.com/script-to-install-latest-hugo-release-on-linux-and-mac/ doesn't take into account OS / Architecture?

**Comment by andreweick** [comment]
@regisphilibert quick question -- what version of Node and what version of NPM are you using?

**Comment by regisphilibert** [comment]
On my local

```
node -v: v15.4.0
npm -v: 7.0.15
```

On netlify we're only setting a node version, not NPM:
```
NODE_VERSION = "15.4.0"
```

**Comment by andreweick** [comment]
@regisphilibert 

I'm trying to do the commands, I'm not sure what they do (or if they are needed!) but they give errors

```
$ REPO=github.com/theNewDynamic/thenewdynamic.com npm run modinit

> hugo-project-template@0.1.0 modinit
> bin/hugo* mod init $REPO

go: /workspaces/eick.com/go.mod already exists
Error: failed to init modules: go command failed: go: /workspaces/eick.com/go.mod already exists

npm notice 
npm notice New minor version of npm available! 7.0.15 -> 7.19.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.19.1
npm notice Run npm install -g npm@7.19.1 to update!
npm notice 
npm ERR! code 255
npm ERR! path /workspaces/eick.com
npm ERR! command failed
npm ERR! command sh -c bin/hugo* mod init $REPO

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vscode/.npm/_logs/2021-07-05T19_14_40_482Z-debug.log
```

Is this command needed?

**Comment by andreweick** [comment]
@regisphilibert This one really blew up :-)


```
vscode ➜ /workspaces/eick.com (devcontainer ✗) $ npm run dev:hugo

> hugo-project-template@0.1.0 dev:hugo
> HUGO_ENV=development bin/hugo* server --minify -D --gc --navigateToChanged --noHTTPCache

Start building sites … 
ERROR 2021/07/05 19:17:34 render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:17:34 render of "page" failed: execute of template failed: template: _default/placeholder.html:5:5: executing "_default/placeholder.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:17:34 render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:17:34 render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:17:34 JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:17:34 failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
Built in 4029 ms
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): Error: Cannot find module 'tailwindcss-break'
Require stack:
- /workspaces/eick.com/assets/css/config/tailwind.config.js
- /workspaces/eick.com/node_modules/tailwindcss/lib/index.js
- /workspaces/eick.com/postcss.config.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/loaders.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/ExplorerBase.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/Explorer.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/index.js
- /workspaces/eick.com/node_modules/postcss-load-config/src/index.js
- /workspaces/eick.com/node_modules/postcss-cli/index.js
- /workspaces/eick.com/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/workspaces/eick.com/assets/css/config/tailwind.config.js:21:5)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/eick.com/assets/css/config/tailwind.config.js',
    '/workspaces/eick.com/node_modules/tailwindcss/lib/index.js',
    '/workspaces/eick.com/postcss.config.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/loaders.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/ExplorerBase.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/Explorer.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/index.js',
    '/workspaces/eick.com/node_modules/postcss-load-config/src/index.js',
    '/workspaces/eick.com/node_modules/postcss-cli/index.js',
    '/workspaces/eick.com/node_modules/postcss-cli/bin/postcss'
  ]
}
npm ERR! code 255
npm ERR! path /workspaces/eick.com
npm ERR! command failed
npm ERR! command sh -c HUGO_ENV=development bin/hugo* server --minify -D --gc --navigateToChanged --noHTTPCache

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vscode/.npm/_logs/2021-07-05T19_17_34_728Z-debug.log
vscode ➜ /workspaces/eick.com (devcontainer ✗) $ 
```

**Comment by andreweick** [comment]
(@regisphilibert sorry to blow up your email, happy Canada day 5 days late). Same error on npm run start

vscode ➜ /workspaces/eick.com (devcontainer ✗) $ npm run start

> hugo-project-template@0.1.0 start
> npm run dev:hugo


> hugo-project-template@0.1.0 dev:hugo
> HUGO_ENV=development bin/hugo* server --minify -D --gc --navigateToChanged --noHTTPCache

Start building sites … 
ERROR 2021/07/05 19:21:47 render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:21:47 render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:21:47 render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:21:47 render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:21:47 JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
ERROR 2021/07/05 19:21:47 failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:5:5: executing "_default/single.html" at <partial "head" .>: error calling partial: execute of template failed: template: partials/head.html:23:3: executing "partials/head.html" at <partialCached "tnd-scripts/tags.html" "all">: error calling partialCached: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/the!new!dynamic/hugo-module-tnd-scripts@v0.0.0-20210512182152-9e0809896a22/partials/tags.html:21:46": execute of template failed: template: partials/tnd-scripts/tags.html:21:46: executing "partials/tnd-scripts/tags.html" at <.Content>: error calling Content: JSBUILD: failed to transform "js/audioplayer.js" (application/javascript): Could not resolve "amplitudejs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
Built in 3207 ms
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): Error: Cannot find module 'tailwindcss-break'
Require stack:
- /workspaces/eick.com/assets/css/config/tailwind.config.js
- /workspaces/eick.com/node_modules/tailwindcss/lib/index.js
- /workspaces/eick.com/postcss.config.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/loaders.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/ExplorerBase.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/Explorer.js
- /workspaces/eick.com/node_modules/cosmiconfig/dist/index.js
- /workspaces/eick.com/node_modules/postcss-load-config/src/index.js
- /workspaces/eick.com/node_modules/postcss-cli/index.js
- /workspaces/eick.com/node_modules/postcss-cli/bin/postcss
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/workspaces/eick.com/assets/css/config/tailwind.config.js:21:5)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/eick.com/assets/css/config/tailwind.config.js',
    '/workspaces/eick.com/node_modules/tailwindcss/lib/index.js',
    '/workspaces/eick.com/postcss.config.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/loaders.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/ExplorerBase.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/Explorer.js',
    '/workspaces/eick.com/node_modules/cosmiconfig/dist/index.js',
    '/workspaces/eick.com/node_modules/postcss-load-config/src/index.js',
    '/workspaces/eick.com/node_modules/postcss-cli/index.js',
    '/workspaces/eick.com/node_modules/postcss-cli/bin/postcss'
  ]
}
npm ERR! code 255
npm ERR! path /workspaces/eick.com
npm ERR! command failed
npm ERR! command sh -c HUGO_ENV=development bin/hugo* server --minify -D --gc --navigateToChanged --noHTTPCache

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vscode/.npm/_logs/2021-07-05T19_21_47_136Z-debug.log
npm ERR! code 255
npm ERR! path /workspaces/eick.com
npm ERR! command failed
npm ERR! command sh -c npm run dev:hugo

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vscode/.npm/_logs/2021-07-05T19_21_47_160Z-debug.log
vscode ➜ /workspaces/eick.com (devcontainer ✗) $

**Comment by regisphilibert** [comment]
I'm not sure what you are trying to do. Re-setup the project?

on `npm run start` fail, it seems `amplitudejs` has not been installed through `npm install` though I can see it on the devDepedencies array of package.json

**Comment by andreweick** [comment]
@regisphilibert thanks.  I did an npm install amplitudes and that seemed to fix some things, now it?

(I'm trying to get the project running on my laptop again -- was working on a different computer...)

```
Start building sites … 
WARN 2021/07/05 19:31:18 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
ERROR 2021/07/05 19:31:18 JSBUILD: failed to transform "tnd-search/instantsearch/index.jsx" (text/jsx): Could not resolve "@meilisearch/instant-meilisearch" (mark it as external to exclude it from the bundle)
Built in 2972 ms
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): Error: Cannot find module 'tailwindcss-break'
Require stack:
```

**Comment by regisphilibert** [comment]
I wonder why it's not being installed when you run `npm install`. This should install all the dependencies listed in your package.json... 🤔

**Comment by regisphilibert** [comment]
I think you might have run `npm run modpack` after the initial setting up had been done which has lead Hugo to mess with your package.json.

Those commands should only be run once when initializing the repository. (Which I had done for you when we upgrade the code)

**Comment by andreweick** [comment]
Indeed -- yes, I did run modpack -- I will remove that from my list.

What I am trying to do is, on a new laptop, what are the commands to run to get a local version running.  I've updated "get-huge.sh" to get the correct OS, Architecture, and version (version from the package.json).  I've got the correct golang version and NODE version installed -- then I ran NPM install, and npm run start?

**Comment by regisphilibert** [comment]
yes! I updated the README so it make more sense after the whole repo setup!

You made a good point that us have the binary in the repo cannot work with dev not sharing the same OS, but then it means on a fresh setup you do need to get the proper hugo binary instead of the one form the repo. Not sure how this work since your edit.

For our own projects, if the binary is on the repo you would just have to run `npm install` once and then `npm run start` for serving/dev, or `npm run deploy` to deploy the assets before publishing

**Comment by andreweick** [comment]
I'll re-look at the README -- 

I updated your get-huge.sh to be OS / ARCH aware -- it even should work for Apple Silicon Macs (according to the internet and XCODE) -- I use a LINUX laptop and (gasp) windows depending on where I am, so I have to make it a bit flexible

**Comment by regisphilibert** [comment]
Yes I understand this is something we'll have to think about for our future onboardings.

**Comment by andreweick** [comment]
I'll push my code to main and then close this issue

**Comment by andreweick** [comment]
Crashed the build -- OOPS

**Comment by andreweick** [comment]
Seems to be a problem with miili search plugin?
