### ISSUE TITLE
Build a responsive picture elements

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#92]
Build responsive picture elements like:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#the_srcset_attribute

https://docs.imgix.com/tutorials/responsive-images-srcset-imgix

**Comment by regisphilibert** [comment]
We'll use the hugo image render hook

**Comment by regisphilibert** [comment]
@andreweick I added the implementation. You can see it in place in the `content/media-test.md` and at https://www.eick.com/media-test/

**Comment by andreweick** [comment]
@regisphilibert -- is the white space to the left and right a function of the theme?  Can we expand that in the theme?

![Screen Shot 2021-06-23 at 11 48 21 AM](https://user-images.githubusercontent.com/1289435/123128378-18c88f00-d419-11eb-9fd6-3a55a393f080.png)

**Comment by regisphilibert** [comment]
I add text to the the page for better context: https://www.eick.com/media-test/
The image is part of the post/page container. This is defined for better readability as @budparr will confirm. Now the image fits within that width, we could make images expand beyond the text, but it's kind of hackish.

**Comment by andreweick** [comment]
Thanks @regisphilibert -- also, can you think of anyway to get the previews to show up in the netlify CMS interface?
