### ISSUE TITLE
On demand builders for photosets

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#93]
Use [Netlify on demand builders](https://docs.netlify.com/configure-builds/on-demand-builders/) for large photosets.

Have the last "2000" (variable set in config.toml) images rendered, then the rest on demand

**Comment by andreweick** [comment]
@regisphilibert what I was trying to say in the meeting -- if On Demand builders wouldn't work with the "finish_deploy" script, I could write a lambda function that emits the "search JSON" payload if that makes more sense in your architecture.

**Comment by regisphilibert** [comment]
@andreweick I'm starting R&D on this and it looks promising but have you changed the url for the S3 api. I'm getting errors on like the second image: https://b2e2t0ibm9.execute-api.us-east-1.amazonaws.com/Prod/photoapi/list/?name=00_57831.jpg

**Comment by andreweick** [comment]
@regisphilibert I'm sorry, I promise I'll get better at this :-). 

I won't touch it (even breath on it)

curl https://m2gfewcae1.execute-api.us-east-1.amazonaws.com/Prod/photoapi/\?name=00_57831.jpg

**Comment by regisphilibert** [comment]
No worry! Thanks for that fast answer ;)

**Comment by regisphilibert** [comment]
this is going great @andreweick do you think you could give me a refreshed list of filenames? Some filenames have no response from the API. Not sure if it's a permanent thing.

**Comment by andreweick** [comment]
@regisphilibert BTW, Thanks for explaining how node uses the "next token" to paginate long returns.  I should have the API extended to return the NAME LIST using next-token in the next few days....

**Comment by regisphilibert** [comment]
quick update @andreweick I recently merged the PR into production so we can start working on a new branch for the paginated API. 

Some problems remain:
- For some reason the _redirects are not working on netlify (on my local? Of course!) so we're using `/.netlify/functions/photo?name=name` on production for the images we generate with on-demand builders
- When using the `builder` Netlify object, we do not have access to `.event.queryStringParameters` which means we cannot retrieve the name of the image from the URL. So for now we're not using the builder but just a regular serverless functions which means the pages are not cached by netlify.

**Comment by andreweick** [comment]
@regisphilibert Awesome job!  Since we are in control of the photos URL, I could put the photo name in the the path (not the query string) if that would help?

2. I see the posts link to "https://60da1f301fe8cd0008fda5b4--www-eick-com.netlify.app/posts/2021-06-23-mclean-soccer-team-picture-black-and-white/", not my eick.com domain -- is that related to https://github.com/andreweick/eick.com/commit/fbe93e697ed648c89ce6e113a6de17e56d3a0f2e?

That CDN is so fast -- I keep thinking it's on a server in my basement.

**Comment by regisphilibert** [comment]
It means we could forgo of the `queryParameters` but I'd have to double check if the string following any given netlify function url is easily accessible from given function.

**Comment by andreweick** [comment]
Yes, if that were the case (the URL is available to the function) then I could change the backend URL to put the name in the URL and not the query string -- let me know

Another for when you get back into it -- the photo page built by the on-demand builders is missing the "tags" generated by the computer vision on the backend...

Go Habs!

**Comment by regisphilibert** [comment]
> Go Habs! 

Thanks! Hopefully it will make me forget the loss of France today...
