### ISSUE TITLE
Externalize root URL into Hugo configuration

### ISSUE THREAD

**Issue by andreweick** [andreweick/eick.com#97]
Currently: 

https://m2gfewcae1.execute-api.us-east-1.amazonaws.com/Prod/

https://m2gfewcae1.execute-api.us-east-1.amazonaws.com/Prod/photoapi/

---
curl https://m2gfewcae1.execute-api.us-east-1.amazonaws.com/Prod/photoapi/\?
name\=10_eicks_pose_by_monolith_.jpg

**Comment by regisphilibert** [comment]
I'll add this as en environment variable for netlify function to consume

**Comment by regisphilibert** [comment]
OK moved this to `S3API_URL` and now used through the on-demand builder and the prebuild plugin.
